// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCndpgmiSO6IZF0D_pI0wLEqYIKOkY2YeA',
    appId: '1:460947965599:web:01b01137392d15111f04aa',
    messagingSenderId: '460947965599',
    projectId: 'skaeng-f6787',
    authDomain: 'skaeng-f6787.firebaseapp.com',
    storageBucket: 'skaeng-f6787.firebasestorage.app',
    measurementId: 'G-C4PKSK9KFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWH8vb7RCM0mJQqFb0rdzF65PKp8v0Rjk',
    appId: '1:460947965599:android:536585e783c032c81f04aa',
    messagingSenderId: '460947965599',
    projectId: 'skaeng-f6787',
    storageBucket: 'skaeng-f6787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSYCsCQOcwp4t7-yrRbygL65t3IbfeUc',
    appId: '1:460947965599:ios:7de5965f940f58e31f04aa',
    messagingSenderId: '460947965599',
    projectId: 'skaeng-f6787',
    storageBucket: 'skaeng-f6787.firebasestorage.app',
    iosBundleId: 'com.skaneng.scanLearnEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrSYCsCQOcwp4t7-yrRbygL65t3IbfeUc',
    appId: '1:460947965599:ios:7de5965f940f58e31f04aa',
    messagingSenderId: '460947965599',
    projectId: 'skaeng-f6787',
    storageBucket: 'skaeng-f6787.firebasestorage.app',
    iosBundleId: 'com.skaneng.scanLearnEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCndpgmiSO6IZF0D_pI0wLEqYIKOkY2YeA',
    appId: '1:460947965599:web:5bb89eca74e9a2951f04aa',
    messagingSenderId: '460947965599',
    projectId: 'skaeng-f6787',
    authDomain: 'skaeng-f6787.firebaseapp.com',
    storageBucket: 'skaeng-f6787.firebasestorage.app',
    measurementId: 'G-GLL366JSW1',
  );
}
